### ISSUE TITLE
Create data parity between `start`, `show`, and `list`

### ISSUE THREAD

**Issue by WilliamMcCumstie** [openflighthpc/flight-desktop#12]
The data about a session should be consistent between the `start`, `show`, and `list` commands. Currently `start`/`show` do not return the `websockify port` nor the `state` of the machine.

This also applies to the new field TBA. This issue specifically refers to the machine readable output. The human readable output does not need to maintain parity (but could?).

NOTE: This issue is not concerned about the format of the data, only its content.

**Comment by ColonelPanicks** [comment]
Closing because:
- Port of VNC session is shown in all 3 places
- State is only shown in list (because `show` will return an error for non-active sessions and `start` is, well, activating a session so shouldn't need the state)
- The above verified via non-interactive sessions (to get the "machine readable output")
